### ISSUE TITLE
[1.11.2 - 1.4.9.4] cascading worldgen lag crash

### ISSUE THREAD

**Issue by Boodaflow** [capnkirok/Inventory-Pets#170]
After starting up a new world, I started exploring near the spawn point until a sudden crash.
This issue seems to involve several mods including: Embers, Inventory Pets, AbyssalCraft, Recurrent Complex, Astral Sorcery, denseores, and Roguelike Dungeons.

[15:09:07] [Server thread/WARN]: Inventory Pets loaded a new chunk (-21, 7 Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.

I tried posting the log in zip, but it wouldn't upload.

**Comment by capnkirok** [comment]
Thanks! Found post about this here: https://www.reddit.com/r/feedthebeast/comments/5x0twz/investigating_extreme_worldgen_lag/

**Comment by capnkirok** [comment]
For any modders reading this:

Fix appears to be to offset your worldgen point to be the center of the chunk... so offset 8 to x and z coordinates so the world gen starts at the center and moves out. Otherwise you overlap with already generated chunks.

**Comment by Boodaflow** [comment]
You're very welcome and thanks for the quick tackle. I'll direct the others this way too.

**Comment by capnkirok** [comment]
Ok, this is fixed in development and will be pushed at next release (1.4.9.5)

**Comment by Boodaflow** [comment]
I see this already added the reference to https://github.com/Vazkii/Quark/issues/412, but I figure I'd relay the stretch of data back just in case you missed it.
