### ISSUE TITLE
Inventory pets bugs out Flight rings

### ISSUE THREAD

**Issue by MiaNbrdr** [capnkirok/Inventory-Pets#562]
I happen to be using Rings of Ascension in my modpack, I added Inventory pets to said modpack with that mod in it and it causes bugs with the Flight ring, Uninstalled Inventory pets fixes the issue but I'd like to know if I can fix it without removing one of these mods, When I try to fly by double pressing space, It'll give me a little boost as it's trying to let me fly but it'll drop me back down and not actually fly. Suggestions appreciated! Edit to add that this isn't a mod specific issue, It's a Flight ring issue, Having same issues with different mods that have a Flight ring

**Comment by capnkirok** [comment]
Yes, known issue (#552) and working on a fix.

**Comment by MiaNbrdr** [comment]
> Yes, known issue (#552) and working on a fix. In the meantime, and I haven't tested this yet, but I think you can just set disableCloudFlying = false and should fix the problem. Of course, the Cloud Pet won't work this way, but it fixes Rings of Ascension. Working on a fix which should be in place by mid-January.

Disabling Cloud pet flight doesn't seem to fix it, but you're already aware of said issue and working on a fix so I'm satisfied. Thank you for the reply :)

**Comment by Eeve2espeon** [comment]
> Yes, known issue (#552) and working on a fix. In the meantime, and I haven't tested this yet, but I think you can just set disableCloudFlying = false and should fix the problem. Of course, the Cloud Pet won't work this way, but it fixes Rings of Ascension. Working on a fix which should be in place by mid-January.

where is that setting exactly? can't find it

**Comment by capnkirok** [comment]
For the record, I've fixed this for many mods on 1.18, 1.19, and 1.20. But I've only fixed it for Curios/Angel Ring on 1.20. Look for the 2.1 release.

**Comment by MiaNbrdr** [comment]
Hello, I hate to drag this on for longer but I need to ask, I tried using Inventory pets again with other mods like RingsofAscension, Angel ring and Better angel ring, It still does not let me fly with the mod installed, I read the other issue that you linked here, You said you had to make a whitelist to enable certain items or mods to work? Did you ever add this? If so, When can I find it because I can't seem to find it. Thanks in advance.

**Comment by capnkirok** [comment]
Hi @MiaNbrdr yes, I did add support, but I also introduced a bug that broke it again. I've left the issue open and is being tracked in #584 

I plan to release the fix this weekend (Sunday). Out of the country at the moment or it would be sooner.

**Comment by MiaNbrdr** [comment]
Appreciate the quick response. Please do enjoy your time away and I'll be patiently waiting for the update! If I happen to find any other issues I will let u know.

**Comment by MiaNbrdr** [comment]
Hi, Would like to confirm that it works now on my end.
Thank you so much for fixing it!
