### ISSUE TITLE
Treetop structures generate floating in Biomes o Plenty biomes

### ISSUE THREAD

**Issue by danygarciagza** [capnkirok/Inventory-Pets#577]
<img width="710" alt="Screenshot 2024-02-08 at 9 14 43 p m" src="https://github.com/capnkirok/Inventory-Pets/assets/159503437/1ef62ab7-aef9-4bd3-94f6-46fdd6d383cf">

**Comment by WenXin20** [comment]
I have this happening for all biomes, including vanilla on 1.20.1.

**Comment by capnkirok** [comment]
Well, that certainly makes it easier to find them! Thanks for the reports.

**Comment by capnkirok** [comment]
Ok, this is fixed in Dev. I lowered the gen location by 3 blocks and tested across a number of biomes. Going to check other versions...

**Comment by capnkirok** [comment]
Yes, same issue on 1.18 and 1.19. Fixed these as well. Should release today.

**Comment by WenXin20** [comment]
This still happens for me with v2.1.1.
In the `data/inventorypets/worldgen/structure` file, `"terrain_adaptation": "beard_thin"` can be added to the json so that terrain will generate below the structure, similar to how villages generate terrain below the houses.

![image](https://github.com/capnkirok/Inventory-Pets/assets/12000593/7aeb5d42-be3f-4b62-9b29-1b0e1b75e6bc)

**Comment by capnkirok** [comment]
Thanks for the feedback and tip. I'll try again!

**Comment by capnkirok** [comment]
Well that seems to help. I'm still seeing trees spawn in water, but at least they're at the right height. Check out 2.1.2 when released and let me know.
