### ISSUE TITLE
Infinite pets with meta pet!!!!

### ISSUE THREAD

**Issue by VitusHS** [capnkirok/Inventory-Pets#643]
If you put your meta pet in your off-hand and then use it, you will get a random pet BUT still have the meta pet in your off-hand?!?!?!?

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/dcd57fdf-080e-4554-800f-9521fedced30" />

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/40d59f94-991f-4a7a-afd6-fb075b5ba184" />

(the pet in the off hand is the meta pet in both pictures)

**Comment by capnkirok** [comment]
That is a terrible bug. Looking into it and will try to get something out in the next week if confirmed.

**Comment by capnkirok** [comment]
Confirmed it's a bug. Fixed in my dev environment. Gonna fix a few more and will release update in a few days.

**Comment by capnkirok** [comment]
Also affects the Siamese Gift (from Siamese Pet).

**Comment by Hajsori** [comment]
The problem is still there in version 2.2.4 for Minecraft 1.21.1 (NeoForge) @capnkirok

**Comment by capnkirok** [comment]
Thanks for the shout. I was not able to replicate at first, but after messing around, I found it. Doesn't happen on the found Meta (the most common), it only happens with 'crafted' Meta Pets (meaning combining 3-4 pets to improve your percentages). Working on a fix now.

**Comment by capnkirok** [comment]
@Hajsori  ok, this is fixed in my development environment. I'll post an update this weekend.

**Comment by Hajsori** [comment]
Alright 👍

**Comment by Hajsori** [comment]
and thanks
